language: python

# python>=3.5 in .github/workflows/python.yml
python:
- 3.4
- 3.5
- 3.6

# required for python >= 3.7
dist: xenial

install:
# pipenv v2020.4.1a2 / v2020.5.28 removed support for python3.4 (in vendored pkg_resources)
# https://github.com/pypa/pipenv/commit/3f9f359c0e563d30a60f0d1e4633eea9f964b610#diff-eec907d96e76285f711fb3cb5ab5469dR92
- pip install --upgrade 'pipenv>=2018.10.9,<v2020.5.28'
- pipenv sync --dev
- if python3 -c 'import sys; sys.exit(sys.version_info < (3, 8))'; then
  pipenv install 'astroid>=2.3.0';
  fi
- pipenv graph

script:
- pipenv run pylint free_disk
- pipenv run pylint --disable=missing-requirement tests/*
- pipenv run pytest
