language: python

python:
- 3.6
- 3.6-dev
- 3.7
- 3.7-dev

# required for python >= 3.7
dist: xenial

install:
- pip install pipenv
- pipenv sync --dev
- pipenv graph

script:
- pipenv run pylint free_disk
- pipenv run pytest
