language: python

python:
- 3.4
- 3.5
- 3.6
- 3.6-dev
- 3.7
- 3.7-dev
- 3.8
- 3.8-dev

# required for python >= 3.7
dist: xenial

install:
- pip install --upgrade pipenv>=2018.10.9
- pipenv sync --dev
- if python3 -c 'import sys; sys.exit(sys.version_info < (3, 8))'; then
  pipenv install 'astroid>=2.3.0';
  fi
- pipenv graph

script:
- pipenv run pylint free_disk
- pipenv run pytest
