# sync with https://github.com/fphammerle/ical2vdir/blob/master/.github/workflows/python.yml

# shown in badge
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
name: tests

on:
  push:
  pull_request:
  schedule:
  - cron: '0 20 * * 5'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version:
        # 3.4 not available
        - 3.5
        - 3.6
        - 3.7
        - 3.8
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install --upgrade pipenv>=2018.10.9
    - run: pipenv install --python "$PYTHON_VERSION" --deploy --dev
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
    - run: if python3 -c 'import sys; sys.exit(sys.version_info < (3, 8))'; then
           pipenv install 'astroid>=2.3.0';
           fi
    - run: pipenv graph
    - run: pipenv run pylint free_disk
    - run: pipenv run pylint --disable=missing-requirement tests/*
    - run: pipenv run pytest
